from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
import sys
from email import utils
from snakemake.utils import Paramspace
import pandas as pd
from os.path import normpath, exists, isdir
from shutil import copyfile, move

# HTTP = HTTPRemoteProvider()
sys.path.append("./scripts")

# Read scenario definitions to construct wildcard and instance patterns from them
trade_scenarios = Paramspace(pd.read_csv("../config/trade_scenarios.csv", dtype=str))


configfile: "../config/config.yaml"

# localrules: all

wildcard_constraints:
    country="[a-zA-Z]+",
    sweep="[a-zA-Z]+",
    rule="(0|[1-9][0-9]?|100)"

rule retrieve_cost_data:
    params:
        version=config['costs']['version'],
    output:
        costs="../resources/technology_data/costs_{cost_year}.csv",
    resources:
        mem_mb=1000,
    retries: 2
    threads: 2
    script:
        "scripts/retrieve_cost_data.py"


# Prepare the trace file prior to running the model
rule retrieve_trace_steel:
    input:
        trace = "../../trace-fneum/trace/resources/networks/default/{cost_year}/shipping-steel/DE-DE/network.nc"
    output:
        trace="../resources/trace/steel_{cost_year}.nc",
    resources:
        mem_mb=5000,
    threads: 2
    run:
        copyfile(input[0], output[0])


rule prepare_wacc:
    input:
        wacc = "../data/wacc-global.csv",
        bus_locations = "../data/bus_locations.csv",
    output:
        wacc = "../resources/wacc-clustered.csv"
    resources:
        mem_mb=5000,
    threads: 2
    notebook:
        "notebooks/prepare-wacc.ipynb"

rule prepare_steel_demand:
    input:
        steel_demand = '../data/demand/ip_market__fabrication.csv',
        bus_locations = "../data/bus_locations.csv",
    output:
        steel_demand = '../resources/steel_demand_clustered_{cost_year}.csv',
    resources:
        mem_mb=5000,
    threads: 2
    notebook:
        "notebooks/prepare-steel-demand.ipynb"



if config["enable"].get("run_supply_chain", True):
    # Individual model calculating the LCoH for up to 60% of maximum potential as demand
    # Stores the resulting LCoH in a csv file
    rule model_lcoh:
        message:
            "Calculating LCoH for region {wildcards.region} for {wildcards.demand_factor}% of estimated maximum hydrogen potential."
        input:
            supply_data ="../data/new_renewables/supply_{region}_2013_cleaned.nc",
            costs = "../resources/technology_data/costs_{cost_year}.csv"
        output:
            results="../resources/lcoh/cost_year~{cost_year}/{region}/results_{demand_factor}.csv",
            network="../resources/lcoh/cost_year~{cost_year}/{region}/network_{demand_factor}.nc",
        threads: 4
        script:
            "scripts/model_lcoh.py"

    rule model_lcox:
        message:
            "Calculating the LCoX of {wildcards.product} for region {wildcards.region} for {wildcards.demand_factor}% of estimated maximum product potential."
        params:
            interest_rate=config["interest_rate"],
        input:
            supply_data ="../data/new_renewables/supply_{region}_2013_cleaned.nc",
            costs = "../resources/technology_data/costs_{cost_year}.csv",
            trace = "../resources/trace/steel_{cost_year}.nc"
        output:
            results="../resources/lco-{product}/cost_year~{cost_year}/{region}/results_{demand_factor}.csv",
            network="../resources/lco-{product}/cost_year~{cost_year}/{region}/network_{demand_factor}.nc",
        threads: 4
        resources:
            mem_mb=8000,
        script:
            "scripts/model_lcox.py"
    

# Read all the individual LCoH values for one region and combine them into a supply curve
# stored as a single csv file per region. Note: the visiual plot includes iron ore costs, the csv without since it is added later in the workflow.

if config["enable"].get("run_supply_curve", True):
    rule create_supply_curve:
        message:
            "Combining individual LCo{wildcards.product[0]} results to create a supply curve for region {wildcards.region}."
        input:
            lco_product_data = lambda wildcards: expand(
                f"../resources/lco-{wildcards.product}/cost_year~{wildcards.cost_year}/{wildcards.region}/results_{{demand_factor}}.csv",
                demand_factor=config["demand_factors"],
                allow_missing=True
            ),
            local_demand = "../data/un_enerdata_demand_2050_final.csv",
            steel_demand = "../resources/steel_demand_clustered_{cost_year}.csv",
        output:
            supply = "../resources/supply_curves/cost_year~{cost_year}/{region}_{product}.csv",
            supply_nodemand = "../resources/supply_curves_nodemand/cost_year~{cost_year}/{region}_{product}.csv",
            supply_curve = "../resources/supply_curves/cost_year~{cost_year}/{region}_{product}.pdf",
        threads: 2
        script:
            "scripts/create_supply_curve.py"



rule create_all_supply_curves:
    input:
        expand(
            "../resources/supply_curves/cost_year~{cost_year}/{region}_{product}.csv",
            cost_year=[2030,2050], region=config["regions"], product=["steel"], allow_missing=True
            ) #cost_year=[2030,2050], region=config["regions"], product=["steel", "hydrogen"]


rule model_trade:
    params:
        iron_ore_potential=config["iron_ore"]["potential_allowance"],
        cost_penalty=config["design"]["cost_penalty"],
        scenarios=config["scenario"],
    input:
        supply_curves_interone = expand(
            "../resources/supply_curves/cost_year~{cost_year}/{region}_{interone}.csv",
            allow_missing=True, region=config["regions"]),
        supply_curves_intertwo = expand(
            "../resources/supply_curves/cost_year~{cost_year}/{region}_{intertwo}.csv",
            allow_missing=True, region=config["regions"]),
        # supply_curves_final = expand(
        #     "../resources/supply_curves/cost_year~{cost_year}/{region}_{final}.csv",
        #     allow_missing=True, region=config["regions"]),
        transport_costs = "../data/transport_costs/steel_r_iron_r.csv",
        trade_options = "../data/trade_opt.csv",
        bus_locations = "../data/bus_locations.csv",
        demand = "../data/un_enerdata_demand_2050_final.csv",
        steel_demand = "../resources/steel_demand_clustered_{cost_year}.csv",
        iron_ore = "../resources/ironore_production_clustered.csv",
        grid_potential = "../data/grid_potential_custom.csv",
    output:
        trade_result = f"../results/{trade_scenarios.wildcard_pattern}/result.csv",
        trade_network = f"../results/{trade_scenarios.wildcard_pattern}/network.nc",
        trade_plot_ironore = f"../results/{trade_scenarios.wildcard_pattern}/map_ironore.pdf",
        trade_plot_ironore_png = f"../results/{trade_scenarios.wildcard_pattern}/map_ironore.png",
        trade_plot_hbi = f"../results/{trade_scenarios.wildcard_pattern}/map_hbi.pdf",
        trade_plot_hbi_png = f"../results/{trade_scenarios.wildcard_pattern}/map_hbi.png",
        trade_plot_steel = f"../results/{trade_scenarios.wildcard_pattern}/map_steel.pdf",
        trade_plot_steel_png = f"../results/{trade_scenarios.wildcard_pattern}/map_steel.png",
    threads: 4
    script:
        "scripts/model_trade.py"




# Povide a rule which triggers creation of all scenarios listed (= rows) in 'scenarios/trade_scenarios.csv'
rule model_trade_all:
    input:
        networks=expand("../results/{scenarios}/network.nc", scenarios=trade_scenarios.instance_patterns),
        results=expand("../results/{scenarios}/result.csv", scenarios=trade_scenarios.instance_patterns),
        trade_plot_ironore=expand("../results/{scenarios}/map_ironore.pdf", scenarios=trade_scenarios.instance_patterns),
        trade_plot_steel=expand("../results/{scenarios}/map_steel.pdf", scenarios=trade_scenarios.instance_patterns),


rule collect_figures:
    input:
        global_supply_curve = "../results/figures_general/{scenario}/global_supply_curve_{sort}_demand_{demand}.pdf", #workflow/notebooks/analysis-coststructure.ipynb
        global_supply_curve_png = "../results/figures_general/{scenario}/global_supply_curve_{sort}_demand_{demand}.png", #workflow/notebooks/analysis-coststructure.ipynb
        electricity_demand = "../results/figures_general/electricity_demand.pdf", #workflow/notebooks/analysis-electricity-demand.ipynb
        electricity_demand_png = "../results/figures_general/electricity_demand.png", #workflow/notebooks/analysis-electricity-demand.ipynb
        electricity_demand_steel = "../results/figures_general/electricity_demand_in_steel.pdf", #workflow/notebooks/analysis-electricity-demand.ipynb
        electricity_demand_steel_png = "../results/figures_general/electricity_demand_in_steel.png", #workflow/notebooks/analysis-electricity-demand.ipynb
        global_map_countries = "../results/figures_general/global_map_countries.pdf", #workflow/notebooks/plot_countries.ipynb
        global_map_countries_png = "../results/figures_general/global_map_countries.png", #workflow/notebooks/plot_countries.ipynb
        cost_comparison = "../results/figures_general/comparison/cost_comparison.pdf", #workflow/notebooks/compare-scenarios.ipynb
        cost_comparison_png = "../results/figures_general/comparison/cost_comparison.png", #workflow/notebooks/compare-scenarios.ipynb
        value_chain_comparison = "../results/figures_general/value_chain_comparison.pdf", #workflow/notebooks/analyse-steel-hbi-split.ipynb
        value_chain_comparison_png = "../results/figures_general/value_chain_comparison.png", #workflow/notebooks/analyse-steel-hbi-split.ipynb
        hourly_analysis = "../results/figures_general/hourly_analysis.pdf", #workflow/notebooks/analysis-hourly.ipynb
        hourly_analysis_png = "../results/figures_general/hourly_analysis.png", #workflow/notebooks/analysis-hourly.ipynb


### Additional rules 

rule create_hydrogen_supply_curve_with_demand:
    message:
        "Combining individual LCoH results to create a supply curve for region {wildcards.region} with demand lines."
    input:
        lcoh_data = expand(
            "../resources/lcoh/cost_year~{cost_year}/{region}/results_{demand_factor}.csv",
            demand_factor=config["demand_factors"],
            allow_missing=True,
        ),
        final_demand_data = "../data/un_enerdata_demand_2050_final.csv"
    output:
        supply_curve="../resources/supply_curves_subtracted_with_demand/cost_year~{cost_year}/{region}_hydrogen.pdf"
    script:
        "scripts/create_hydrogen_supply_curve_with_demand.py"
rule create_all_supply_curves_with_demand:
    input:
        expand(
            "../resources/supply_curves_subtracted_with_demand/cost_year~{cost_year}/{region}_hydrogen.pdf", cost_year=[2030,2050], region=config["regions"], allow_missing=True
            )
            

# rule model_trade_singlestage:
#     input:
#         supply_curves = expand(
#             "../resources/supply_curves/cost_year~{cost_year}/{region}_{product}.csv",
#             allow_missing=True, region=config["regions"]    ),
#         transport_costs = "../data/transport_costs/{transport_cost}.csv",
#         trade_options = "../data/trade_opt.csv",
#         bus_locations = "../data/bus_locations.csv",
#         demand = "../data/un_enerdata_demand_2050_final.csv",
#         steel_demand = "../resources/steel_production_clustered.csv",
#     output:
#         trade_result = f"../results/{trade_scenarios.wildcard_pattern}/result.csv",
#         trade_network = f"../results/{trade_scenarios.wildcard_pattern}/network.nc",
#         trade_plot = f"../results/{trade_scenarios.wildcard_pattern}/plot.pdf"
#     script:
#         "scripts/model_trade_singlestage.py"


### Toolkit

# Under development
# rule input_cost_comp:
#     message: 
#         "Comparing input costs"

#     notebook:
#         "workflow/notebooks/input-cost-comp.ipynb"