# SPDX-License-Identifier: CC0-1.0

name: shift
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.10
- pip

# Inhouse packages
- pypsa>=0.32.1
- atlite>=0.3
- linopy>=0.4.4

# Dependencies of the workflow itself
- openpyxl
- seaborn
- snakemake-minimal>=9
- snakemake-storage-plugin-http>=0.3
- snakemake-executor-plugin-slurm
- snakemake-executor-plugin-cluster-generic
- yaml
- pytables
- lxml
- numpy
- pandas>=2.1
- geopandas>=1
- xarray>=2024.03.0
- netcdf4
- libgdal-netcdf
- networkx
- scipy
- shapely>=2.0
- matplotlib
- geopy
- tqdm
- geojson
- graphviz
- wbdata
- searoute

# GIS dependencies:
- cartopy

# Development dependencies
- jupyter
- ipython
- pre-commit
- ruff
- pylint

- pip:
  - gurobipy
  - highspy
  - wbgapi
  - pypsatopo
